server/aircraft/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from .views import HomeView, RegisterView, api_root

urlpatterns = [

    # Apps
    path('', HomeView.as_view(), name='home'),
    path('', include('apps.users.urls', namespace="users")),
    path('', include('apps.production.urls', namespace="production")),
    path('', include('apps.factory.urls', namespace="factory")),

    # Rest API
    path('api/v1/', api_root),

    # Authentication
    re_path(r'^login/$', auth_views.LoginView.as_view(), {'template_name': 'registration/login.html'}, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),

    # Built in urls
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/v1/auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/v1/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/v1/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/v1/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

server/apps/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('teams/', views.TeamsView.as_view(), name='teams'),
    path('teams/<int:pk>/', views.TeamsDetailView.as_view(), name='teams-detail'),
    path('teams/<int:pk>/members/', views.TeamsMembersView.as_view(), name='teams-members'),

    path('api/v1/users/', views.UserListViewSet.as_view(), name='api-user-list'),
    path('api/v1/users/<str:username>/', views.UserDetailViewSet.as_view(), name='api-user-detail'),
    path('api/v1/teams/', views.TeamsViewSet.as_list(), name='api-team-list'),
    path('api/v1/teams/<int:pk>', views.TeamsViewSet.as_detail(), name='api-team-detail'),
]

server/templates/teams/teams.html
{% extends "base.html" %}
{% block header %}
    {% include "header.html" %}
{% endblock header %}
{% block content %}
<div class="py-10">
    <header>
      <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div>
            <div>
              <nav class="sm:hidden" aria-label="Back">
                  <a href="javascript:history.back()" class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700">
                    <svg class="-ml-1 mr-1 size-5 shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
                      <path fill-rule="evenodd" d="M11.78 5.22a.75.75 0 0 1 0 1.06L8.06 10l3.72 3.72a.75.75 0 1 1-1.06 1.06l-4.25-4.25a.75.75 0 0 1 0-1.06l4.25-4.25a.75.75 0 0 1 1.06 0Z" clip-rule="evenodd" />
                    </svg>
                    Back
                  </a>
              </nav>
              <nav class="hidden sm:flex" aria-label="Breadcrumb">
                  <ol role="list" class="flex items-center space-x-4">
                    <li>
                      <div class="flex">
                        <a href="{% url 'users:teams' %}" class="text-sm font-medium text-gray-500 hover:text-gray-700">Teams</a>
                      </div>
                    </li>
                    {% block page_breadcrumb %}{% endblock %}
                  </ol>
              </nav>
            </div>
            <div class="mt-2 md:flex md:items-center md:justify-between">
              <div class="min-w-0 flex-1">
                <h2 class="text-2xl/7 font-bold text-gray-900 sm:truncate sm:text-3xl sm:tracking-tight">{% block page_title %}Aircraft Production Teams{% endblock %}</h2>
              </div>
              <div class="mt-4 flex shrink-0 md:ml-4 md:mt-0">
                {% block page_actions %}{% endblock %}
              </div>
            </div>
          </div>
      </div>
    </header>
    <main>
      {% block page_content %}{% endblock %}
    </main>
</div>
{% endblock content %}
{% block footer %}
{% include "footer.html" %}
{% endblock footer %}

server/templates/teams/teams_add_member.html
{% extends "teams/teams.html" %}
{% block page_breadcrumb %}
<li>
    <div class="flex items-center">
        <svg class="size-5 shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
        <path fill-rule="evenodd" d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
        </svg>
        <a href="{% url 'users:teams-detail' pk=object.pk %}" class="ml-4 text-sm font-medium text-gray-500 hover:text-gray-700">{{ object.name }}</a>
    </div>
</li>
{% endblock %}
{% block page_content %}
<form class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8" method="post">
    {% csrf_token %}
    <div class="sm:flex sm:items-center">
        <div class="sm:flex-auto">
            <h1 class="text-base font-semibold text-gray-900">List of user</h1>
            <p class="mt-2 text-sm text-gray-700">Select users you want to add to {{ object.name }}.</p>
        </div>
        <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
            <button type="submit" class="block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                Add member(s)
            </button>
        </div>
    </div>
    <div class="mt-8 flow-root">
        <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
                <table class="min-w-full divide-y divide-gray-300">
                    <thead>
                        <tr>
                            <th scope="col"
                                class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Username</th>
                            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Name</th>
                            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Email address</th>
                            <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
                                <span class="sr-only">Remove</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-200">
                        {% for member in user_list %}
                            <tr>
                                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">{{ member.username }}</td>
                                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ member.first_name }} {{ member.last_name }}</td>
                                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ member.email }}</td>
                                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                                    <input name="add_users" value="{{ member.pk }}" type="checkbox" class="col-start-1 row-start-1 appearance-none rounded border border-gray-300 bg-white checked:border-indigo-600 checked:bg-indigo-600 indeterminate:border-indigo-600 indeterminate:bg-indigo-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 disabled:border-gray-300 disabled:bg-gray-100 disabled:checked:bg-gray-100 forced-colors:appearance-auto">
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>    
</form>
{% endblock %}

server/templates/teams/teams_detail.html
{% extends "teams/teams.html" %}
{% block page_breadcrumb %}
<li>
    <div class="flex items-center">
        <svg class="size-5 shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
        <path fill-rule="evenodd" d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
        </svg>
        <a href="{% url 'users:teams-detail' pk=object.pk %}" class="ml-4 text-sm font-medium text-gray-500 hover:text-gray-700">{{ object.name }}</a>
    </div>
</li>
{% endblock %}
{% block page_content %}
<div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
    <div class="sm:flex sm:items-center">
        <div class="sm:flex-auto">
            <h1 class="text-base font-semibold text-gray-900">List of members</h1>
            <p class="mt-2 text-sm text-gray-700">A list of all the users in {{ object.name }} including their name, title and email.</p>
        </div>
        <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
            <a href="{% url 'users:teams-members' pk=object.pk %}" type="button" class="inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">
                Manage
            </a>
        </div>
    </div>
    <div class="mt-8 flow-root">
        <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
                <table class="min-w-full divide-y divide-gray-300">
                    <thead>
                        <tr>
                            <th scope="col"
                                class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Username</th>
                            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Name</th>
                            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Email address</th>
                            <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
                                <span class="sr-only">Remove</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-200">
                        {% for member in object.user_set.all %}
                            <tr>
                                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">{{ member.username }}</td>
                                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ member.first_name }} {{ member.last_name }}</td>
                                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ member.email }}</td>
                                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                                    <!-- Close your eyes please... -->
                                    <form method="post">
                                        {% csrf_token %}
                                        <input value={{ member.pk }} type="hidden" name="remove">
                                        <button type="submit" class="text-indigo-600 hover:text-indigo-900">Remove</button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="flex items-center mt-8 mb-8" aria-hidden="true"></div>
    <div class="sm:flex sm:items-center">
        <div class="sm:flex-auto">
            <h1 class="text-base font-semibold text-gray-900">Permissions</h1>
            <p class="mt-2 text-sm text-gray-700">A list of all possible actions </p>
        </div>
    </div>
    <div class="mt-8 flow-root">
        <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
                <table class="min-w-full divide-y divide-gray-300">
                    <thead>
                        <tr>
                            <th scope="col"
                                class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Codename</th>
                            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Description</th>
                            <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
                                <span class="sr-only">Remove</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-200">
                        {% for permission in object.permissions.all %}
                            <tr>
                                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">{{ permission.codename }}</td>
                                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ member.first_name }} {{ permission.name }}</td>
                                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                                    <!-- Close your eyes please... -->
                                    <form method="post">
                                        {% csrf_token %}
                                        <input value={{ permission.codename }} type="hidden" name="remove">
                                        <button type="submit" class="text-indigo-600 hover:text-indigo-900">Remove</button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

server/templates/teams/teams_index.html
{% extends "teams/teams.html" %}
{% block page_content %}
<div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
    <div class="mt-6 grid grid-cols-1 gap-x-8 gap-y-8 sm:grid-cols-2 sm:gap-y-10 lg:grid-cols-4">
        {% for team in team_list %}
            <div class="group relative">
                <div class="relative">
                <div class="aspect-[4/3] w-full rounded-lg bg-gray-200 object-cover"></div>
                <div class="absolute inset-0 flex items-end p-4 opacity-0 group-hover:opacity-100" aria-hidden="true">
                    <div class="w-full rounded-md bg-white/75 px-4 py-2 text-center text-sm font-medium text-gray-900 backdrop-blur backdrop-filter">Settings</div>
                </div>
                </div>
                <div class="mt-4 flex items-center justify-between space-x-8 text-base font-medium text-gray-900">
                    <h3>
                        <a href="{% url 'users:teams-detail' pk=team.id %}">
                        <span aria-hidden="true" class="absolute inset-0"></span>
                        {{ team.name }}
                        </a>
                    </h3>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}