server/aircraft/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from .views import HomeView, RegisterView, api_root

urlpatterns = [

    # Apps
    path('', HomeView.as_view(), name='home'),
    path('', include('apps.users.urls', namespace="users")),
    path('', include('apps.production.urls', namespace="production")),
    path('', include('apps.factory.urls', namespace="factory")),

    # Rest API
    path('api/v1/', api_root),

    # Authentication
    re_path(r'^login/$', auth_views.LoginView.as_view(), {'template_name': 'registration/login.html'}, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),

    # Built in urls
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/v1/auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/v1/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/v1/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/v1/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

server/apps/factory/urls.py
from django.urls import path
from apps.factory import views

app_name = 'factory'

urlpatterns = [
    path('factory/', views.FactoryView.as_view(), name='index'),
    path('factory/part/<slug:pk>/', views.FactoryPartDetailView.as_view(), name='part-detail'),
    path('factory/model/<slug:pk>/', views.FactoryModelDetailView.as_view(), name='model-detail'),

    path('api/v1/factory/model/', views.FactoryModelViewSet.as_list(), name='api-factory-model-list'),
    path('api/v1/factory/model/<slug:name>/', views.FactoryModelViewSet.as_detail(), name='api-factory-model-detail'),
    path('api/v1/factory/part/', views.FactoryPartViewSet.as_list(), name='api-factory-part-list'),
    path('api/v1/factory/part/<slug:name>/', views.FactoryPartViewSet.as_detail(), name='api-factory-part-detail'),

]

server/apps/factory/models.py
from django.db import models
from django.contrib.auth import get_user_model
from apps.production.models import AircraftModel, AircraftPart
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType

User = get_user_model()
# Create your models here.
class AircraftModelFactory(models.Model):
    
    model_type = models.ForeignKey(AircraftModel, on_delete=models.CASCADE, related_name='model_type')
    made_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='model_made_by')
    made_at = models.DateTimeField(auto_now_add=True, null=False)

    class Meta:
        ordering = ('made_at',)


class AircraftPartFactory(models.Model):

    part_type = models.ForeignKey(AircraftPart, on_delete=models.CASCADE, related_name='part_type')
    part_of = models.ForeignKey(AircraftModel, on_delete=models.CASCADE, related_name='part_of')
    made_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='part_made_by')
    made_at = models.DateTimeField(auto_now_add=True, null=False)
    used_by = models.ForeignKey(AircraftModelFactory, on_delete=models.CASCADE, null=True, related_name='part_used_by')

    @property
    def is_available(self):
        return self.used_by is None

    class Meta:
        ordering = ('made_at',)


@receiver(post_save, sender=AircraftPart, dispatch_uid="update_part_permissions")
def update_part_permissions(sender, instance, **kwargs):
    # TODO - Reverte item creation if any of the permissions creation fails
    Permission.objects.get_or_create(codename=f'can_add_{instance.name}', name=f'Can add {instance.name}', content_type=ContentType.objects.get_for_model(AircraftPartFactory))
    Permission.objects.get_or_create(codename=f'can_change_{instance.name}', name=f'Can change {instance.name}', content_type=ContentType.objects.get_for_model(AircraftPartFactory))
    Permission.objects.get_or_create(codename=f'can_delete_{instance.name}', name=f'Can delete {instance.name}', content_type=ContentType.objects.get_for_model(AircraftPartFactory))
    Permission.objects.get_or_create(codename=f'can_view_{instance.name}', name=f'Can view {instance.name}', content_type=ContentType.objects.get_for_model(AircraftPartFactory))
    

server/apps/factory/forms.py
from django import forms
from django.forms import fields, widgets

server/apps/factory/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView
from apps.production.models import AircraftModel, AircraftPart
from apps.core.mixins import CrudViewSet
from . import models, serializers
from django.db import IntegrityError, transaction

# Create your views here.
class FactoryView(TemplateView):
    template_name = 'factory/factory_index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_factory'] = AircraftModel.objects.all()
        context['part_factory'] = AircraftPart.objects.all()
        return context

class FactoryPartDetailView(DetailView):
    model = AircraftPart
    template_name = 'factory/factory_part.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['part_list'] = models.AircraftPartFactory.objects.filter(part_type=self.object).order_by('-made_at')
        context['model_list'] = AircraftModel.objects.all()
        return context
    
    def post(self, request, *args, **kwargs):
        # TODO handle errors
        if 'model' in request.POST and 'pk' in kwargs:
            models.AircraftPartFactory.objects.create(
                part_type=AircraftPart.objects.get(pk=kwargs['pk']),
                part_of=AircraftModel.objects.get(pk=request.POST['model']),
                made_by=request.user
            )
        return self.get(request, *args, **kwargs)

class FactoryModelDetailView(DetailView):
    model = AircraftModel
    template_name = 'factory/factory_model.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['part_list'] = AircraftPart.objects.all()
        context['model_list'] = models.AircraftModelFactory.objects.filter(model_type=self.object).order_by('-made_at')
        return context

    def post(self, request, *args, **kwargs):
        if 'pk' in kwargs:
            try:
                with transaction.atomic():
                    model_type = AircraftModel.objects.get(pk=kwargs['pk'])
                    model = models.AircraftModelFactory.objects.create(
                        model_type=model_type,
                        made_by=request.user
                    )
                    for part_type in AircraftPart.objects.all():
                        part: models.AircraftPartFactory = models.AircraftPartFactory.objects.filter(
                            part_type=part_type,
                            part_of=model_type,
                            used_by=None
                        ).first()
                        if part is None:
                            raise IntegrityError
                        else:
                            part.used_by = model
                            part.save()
            except IntegrityError:
                # TODO more stuff
                print('IntegrityError')
        return self.get(request, *args, **kwargs)

class FactoryModelViewSet(CrudViewSet):
    serializer_class = serializers.FactoryModelSerializer
    lookup_field = 'model_type__name'
    lookup_url_kwarg = 'name'

    def get_queryset(self):
        return models.AircraftModelFactory.objects.all()

class FactoryPartViewSet(CrudViewSet):
    serializer_class = serializers.FactoryPartSerializer
    lookup_field = 'part_type__name'
    lookup_url_kwarg = 'name'

    def get_queryset(self):
        return models.AircraftPartFactory.objects.all()

server/templates/factory/factory.html
{% extends "base.html" %}
{% block header %}
    {% include "header.html" %}
{% endblock header %}
{% block content %}
<div class="py-10">
    <header>
      <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div>
            <div>
              <nav class="sm:hidden" aria-label="Back">
                  <a href="javascript:history.back()" class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700">
                    <svg class="-ml-1 mr-1 size-5 shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
                      <path fill-rule="evenodd" d="M11.78 5.22a.75.75 0 0 1 0 1.06L8.06 10l3.72 3.72a.75.75 0 1 1-1.06 1.06l-4.25-4.25a.75.75 0 0 1 0-1.06l4.25-4.25a.75.75 0 0 1 1.06 0Z" clip-rule="evenodd" />
                    </svg>
                    Back
                  </a>
              </nav>
              <nav class="hidden sm:flex" aria-label="Breadcrumb">
                  <ol role="list" class="flex items-center space-x-4">
                    <li>
                      <div class="flex">
                        <a href="{% url 'factory:index' %}" class="text-sm font-medium text-gray-500 hover:text-gray-700">Factory</a>
                      </div>
                    </li>
                    {% block page_breadcrumb %}{% endblock %}
                  </ol>
              </nav>
            </div>
            <div class="mt-2 md:flex md:items-center md:justify-between">
              <div class="min-w-0 flex-1">
                <h2 class="text-2xl/7 font-bold text-gray-900 sm:truncate sm:text-3xl sm:tracking-tight">{% block page_title %}Aircraft Factory{% endblock %}</h2>
              </div>
              <div class="mt-4 flex shrink-0 md:ml-4 md:mt-0">
                {% block page_actions %}{% endblock %}
              </div>
            </div>
          </div>
      </div>
    </header>
    <main>
      {% block page_content %}{% endblock %}
    </main>
</div>
{% endblock content %}
{% block footer %}
{% include "footer.html" %}
{% endblock footer %}

server/templates/factory/factory_index.html
{% extends "factory/factory.html" %}
{% block page_content %}


<div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between space-x-4">
        <h2 class="text-lg font-medium text-gray-900">Model of aircraft you can create</h2>
    </div>
    <div class="mt-6 grid grid-cols-1 gap-x-8 gap-y-8 sm:grid-cols-2 sm:gap-y-10 lg:grid-cols-4">
        {% for model in model_factory %}
            <div class="group relative">
                <div class="relative">
                <img src="https://cdn.baykartech.com/media/upload/userFormUpload/HfKd71PR8Fqln30Qu1VSVY7ujAvC9VgL.png" class="aspect-[4/3] w-full rounded-lg bg-gray-100 object-cover">
                <div class="absolute inset-0 flex items-end p-4 opacity-0 group-hover:opacity-100" aria-hidden="true">
                    <div class="w-full rounded-md bg-white/75 px-4 py-2 text-center text-sm font-medium text-gray-900 backdrop-blur backdrop-filter">Create Models</div>
                </div>
                </div>
                <div class="mt-4 flex items-center justify-between space-x-8 text-base font-medium text-gray-900">
                    <h3>
                        <a href="{% url 'factory:model-detail' pk=model.name %}">
                        <span aria-hidden="true" class="absolute inset-0"></span>
                        {{ model.name }}
                        </a>
                    </h3>
                </div>
                <p class="mt-1 text-sm text-gray-500">{{ model.desc }}</p>
            </div>
        {% endfor %}
    </div>
</div>

<div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between space-x-4">
        <h2 class="text-lg font-medium text-gray-900">Part of aircraft you can create</h2>
    </div>
    <div class="mt-6 grid grid-cols-1 gap-x-8 gap-y-8 sm:grid-cols-2 sm:gap-y-10 lg:grid-cols-4">
        {% for part in part_factory %}
            <div class="group relative">
                <div class="relative">
                <img src="https://cdn.baykartech.com/media/upload/userFormUpload/FcLUmeJZLYReOgicr8GyC32dEQauCGcO.jpeg" alt="Payment application dashboard screenshot with transaction table, financial highlights, and main clients on colorful purple background." class="aspect-[4/3] w-full rounded-lg bg-gray-100 object-cover">
                <div class="absolute inset-0 flex items-end p-4 opacity-0 group-hover:opacity-100" aria-hidden="true">
                    <div class="w-full rounded-md bg-white/75 px-4 py-2 text-center text-sm font-medium text-gray-900 backdrop-blur backdrop-filter">Create Part</div>
                </div>
                </div>
                <div class="mt-4 flex items-center justify-between space-x-8 text-base font-medium text-gray-900">
                    <h3>
                        <a href="{% url 'factory:part-detail' pk=part.name %}">
                        <span aria-hidden="true" class="absolute inset-0"></span>
                        {{ part.name }}
                        </a>
                    </h3>
                </div>
                <p class="mt-1 text-sm text-gray-500">{{ part.desc }}</p>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

server/templates/factory/factory_model.html
{% extends "factory/factory.html" %}
{% block page_content %}

<div class="bg-white">
    <div class="mx-auto px-4 sm:px-6 sm:py-8 lg:max-w-7xl lg:px-8">
        <!-- Product -->
        <div class="lg:grid lg:grid-cols-7 lg:grid-rows-1 lg:gap-x-8 lg:gap-y-10 xl:gap-x-16">
            <!-- Product image -->
            <div class="lg:col-span-4 lg:row-end-1">
                <img src="https://cdn.baykartech.com/media/upload/userFormUpload/HfKd71PR8Fqln30Qu1VSVY7ujAvC9VgL.png"
                    alt="Sample of 30 icons with friendly and fun details in outline, filled, and brand color styles."
                    class="aspect-[4/3] w-full rounded-lg bg-gray-100 object-cover">
            </div>

            <!-- Product details -->
            <div class="mt-14 max-w-2xl sm:mt-16 lg:col-span-3 lg:row-span-2 lg:row-end-2 lg:mt-0 lg:max-w-none">
                <div class="flex flex-col-reverse">
                    <div class="mt-4">
                        <h1 class="text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">{{ object.name }}</h1>

                        <h2 id="information-heading" class="sr-only">Part information</h2>
                        <p class="mt-2 text-sm text-gray-500">Version 1.0 (Updated <time datetime="2021-06-05">June 5,2021</time>)
                        </p>
                    </div>
                </div>

                <p class="mt-6 text-gray-500">{{ object.desc }}</p>

                <form class="mt-10" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="flex w-full items-center justify-center mt-5 rounded-md border border-transparent bg-indigo-600 px-8 py-2 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-50">
                        Build now
                    </button>
                </form>

                <div class="mt-10 border-t border-gray-200 pt-10">
                    <h3 class="text-sm font-medium text-gray-900">Factory policy (required part)</h3>
                    <div class="mt-4">
                        <ul role="list" class="list-disc space-y-1 pl-5 text-sm/6 text-gray-500 marker:text-gray-300">
                            {% for part in part_list %}
                                <li class="pl-2">{{ part.name }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="mx-auto mt-16 w-full max-w-2xl lg:col-span-4 lg:mt-0 lg:max-w-none">
                <ul role="list" class="divide-y divide-gray-100">
                    {% for model in model_list %}
                    <li class="flex items-center justify-between gap-x-6 py-5">
                        <div class="min-w-0">
                            <div class="flex items-start gap-x-3">
                                <p class="text-sm/6 font-semibold text-gray-900">{{ model.model_type.name }}</p>
                            </div>
                            <div class="mt-1 flex items-center gap-x-2 text-xs/5 text-gray-500">
                                <p class="whitespace-nowrap">Made by {{ model.made_by }}</p>
                                <svg viewBox="0 0 2 2" class="size-0.5 fill-current">
                                    <circle cx="1" cy="1" r="1" />
                                </svg>
                                <p class="truncate">{{ model.made_at }}</p>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}

server/templates/factory/factory_part.html
{% extends "factory/factory.html" %}
{% block page_content %}

<div class="bg-white">
    <div class="mx-auto px-4 sm:px-6 sm:py-8 lg:max-w-7xl lg:px-8">
        <!-- Product -->
        <div class="lg:grid lg:grid-cols-7 lg:grid-rows-1 lg:gap-x-8 lg:gap-y-10 xl:gap-x-16">
            <!-- Product image -->
            <div class="lg:col-span-4 lg:row-end-1">
                <img src="https://cdn.baykartech.com/media/upload/userFormUpload/FcLUmeJZLYReOgicr8GyC32dEQauCGcO.jpeg"
                    alt="Sample of 30 icons with friendly and fun details in outline, filled, and brand color styles."
                    class="aspect-[4/3] w-full rounded-lg bg-gray-100 object-cover">
            </div>

            <!-- Product details -->
            <div class="mt-14 max-w-2xl sm:mt-16 lg:col-span-3 lg:row-span-2 lg:row-end-2 lg:mt-0 lg:max-w-none">
                <div class="flex flex-col-reverse">
                    <div class="mt-4">
                        <h1 class="text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl">{{ object.name }}</h1>

                        <h2 id="information-heading" class="sr-only">Part information</h2>
                        <p class="mt-2 text-sm text-gray-500">Version 1.0 (Updated <time datetime="2021-06-05">June 5,
                                2021</time>)
                        </p>
                    </div>
                </div>

                <p class="mt-6 text-gray-500">{{ object.desc }}</p>

                <form class="mt-10" method="POST">
                    {% csrf_token %}
                    <label for="model" class="block text-sm/6 font-medium text-gray-900">Model</label>
                    <div class="mt-2 grid grid-cols-1">
                        <select id="model" name="model" class="col-start-1 row-start-1 w-full appearance-none rounded-md bg-white py-1.5 pl-3 pr-8 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6">
                            {% for model in model_list %}
                                <option value={{ model.name }}>{{ model.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="flex w-full items-center justify-center mt-5 rounded-md border border-transparent bg-indigo-600 px-8 py-2 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-50">
                        Create now
                    </button>
                </form>

                <div class="mt-10 border-t border-gray-200 pt-10">
                    <h3 class="text-sm font-medium text-gray-900">Factory policy</h3>
                    <div class="mt-4">
                        <ul role="list" class="list-disc space-y-1 pl-5 text-sm/6 text-gray-500 marker:text-gray-300">
                            <li class="pl-2">Only privileged members</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="mx-auto mt-16 w-full max-w-2xl lg:col-span-4 lg:mt-0 lg:max-w-none">
                <ul role="list" class="divide-y divide-gray-100">
                    {% for part in part_list %}
                    <li class="flex items-center justify-between gap-x-6 py-5">
                        <div class="min-w-0">
                            <div class="flex items-start gap-x-3">
                                <p class="text-sm/6 font-semibold text-gray-900">{{ part.part_type }} for {{ part.part_of }}</p>
                                {% if part.is_available %}
                                <p class="mt-0.5 whitespace-nowrap rounded-md bg-gray-50 px-1.5 py-0.5 text-xs font-medium text-gray-600 ring-1 ring-inset ring-gray-500/10">Available</p>
                                {% else %}
                                <p class="mt-0.5 whitespace-nowrap rounded-md bg-green-50 px-1.5 py-0.5 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">Already used</p>
                                {% endif %}
                            </div>
                            <div class="mt-1 flex items-center gap-x-2 text-xs/5 text-gray-500">
                                <p class="whitespace-nowrap">Made by {{ part.made_by }}</p>
                                <svg viewBox="0 0 2 2" class="size-0.5 fill-current">
                                    <circle cx="1" cy="1" r="1" />
                                </svg>
                                <p class="truncate">{{ part.made_at }}</p>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>



{% endblock %}