server/aircraft/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from .views import HomeView, RegisterView, api_root

urlpatterns = [

    # Apps
    path('', HomeView.as_view(), name='home'),
    path('', include('apps.users.urls', namespace="users")),
    path('', include('apps.production.urls', namespace="production")),
    path('', include('apps.factory.urls', namespace="factory")),

    # Rest API
    path('api/v1/', api_root),

    # Authentication
    re_path(r'^login/$', auth_views.LoginView.as_view(), {'template_name': 'registration/login.html'}, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),

    # Built in urls
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/v1/auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/v1/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/v1/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/v1/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

server/apps/production/urls.py
from django.urls import path
from apps.production import views

app_name = 'production'

urlpatterns = [
    path('production/', views.index, name='index'),
    path('production/model/', views.AircraftModelView.as_view(), name='model'),
    path('production/model/create', views.AircraftModelCreateView.as_view(), name='model-create'),
    path('production/part/', views.AircraftPartView.as_view(), name='part'),
    path('production/part/create', views.AircraftPartCreateView.as_view(), name='part-create'),

    path('api/v1/production/model/', views.AircraftModelViewSet.as_list(), name='api-prod-model-list'),
    path('api/v1/production/model/<str:name>', views.AircraftModelViewSet.as_detail(), name='api-prod-model-detail'),
    path('api/v1/production/part/', views.AircraftPartViewSet.as_list(), name='api-prod-part-list'),
    path('api/v1/production/part/<str:name>', views.AircraftPartViewSet.as_detail(), name='api-prod-part-detail'),
]

server/apps/production/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()
# Create your models here.
class AircraftModel(models.Model):
    name = models.SlugField(max_length=50, primary_key=True, blank=False)
    desc = models.CharField(max_length=300, blank=True, default='')

    def __str__(self):
        return self.name

class AircraftPart(models.Model):
    name = models.SlugField(max_length=50, primary_key=True, blank=False)
    desc = models.CharField(max_length=300, blank=True, default='')

    def __str__(self):
        return self.name
    

server/apps/production/forms.py
from django import forms
from django.forms import fields, widgets
from apps.production.models import AircraftModel, AircraftPart

class AircraftModelForm(forms.ModelForm):
    class Meta:
        model = AircraftModel
        fields = '__all__'
        labels = {
            'name': 'Aircraft Type Name',
            'desc': 'Description',
        }
        widgets = {
            'name': forms.TextInput(attrs={'classes': 'form-control'}),
            'desc': forms.Textarea(attrs={'classes': 'form-control', 'rows': 3}),
        }

class AircraftPartForm(forms.ModelForm):
    class Meta:
        model = AircraftPart
        fields = '__all__'
        labels = {
            'name': 'Aircraft Part Name',
            'desc': 'Description',
        }
        widgets = {
            'name': forms.TextInput(attrs={'classes': 'form-control'}),
            'desc': forms.Textarea(attrs={'classes': 'form-control', 'rows': 3}),
        }


        

server/aircraft/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView
from rest_framework import permissions
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework.reverse import reverse
from drf_spectacular.utils import extend_schema

# Create your views here.
class HomeView(TemplateView):
    template_name = 'home.html'

class RegisterView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = 'registration/register.html'

@extend_schema(exclude=True)
@api_view(('GET',))
@permission_classes((permissions.AllowAny,))
def api_root(request, format=None):
    return Response({
        'users': reverse('users:api-user-list', request=request, format=format),
        'teams': reverse('users:api-team-list', request=request, format=format),
        'production-model': reverse('production:api-prod-model-list', request=request, format=format),
        'production-part': reverse('production:api-prod-part-list', request=request, format=format),
        'factory-model': reverse('factory:api-factory-model-list', request=request, format=format),
        'factory-part': reverse('factory:api-factory-part-list', request=request, format=format),
    })

server/apps/production/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView, CreateView
from django.urls import reverse_lazy
from apps.core.mixins import CrudViewSet
from . import serializers, models, forms

# Create your views here.
@login_required
def index(request):
    return render(request, 'production/aircraft_index.html')

class AircraftModelView(TemplateView):
    template_name = 'production/aircraft_model.html'
    model = models.AircraftModel

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = {
            'model_list': self.model.objects.all(),
        }
        return context

class AircraftModelCreateView(CreateView):
    form_class = forms.AircraftModelForm
    success_url = reverse_lazy('production:model')
    template_name = 'production/aircraft_model_create.html'

class AircraftPartView(TemplateView):
    template_name = 'production/aircraft_part.html'
    model = models.AircraftPart

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = {
            'part_list': self.model.objects.all(),
        }
        return context

class AircraftPartCreateView(CreateView):
    form_class = forms.AircraftPartForm
    success_url = reverse_lazy('production:part')
    template_name = 'production/aircraft_part_create.html'


class AircraftModelViewSet(CrudViewSet):
    serializer_class = serializers.AircraftModelSerializer
    lookup_field = 'name'
    lookup_url_kwarg = 'name'

    def get_queryset(self):
        return models.AircraftModel.objects.all()

class AircraftPartViewSet(CrudViewSet):
    serializer_class = serializers.AircraftPartSerializer
    lookup_field = 'name'
    lookup_url_kwarg = 'name'

    def get_queryset(self):
        return models.AircraftPart.objects.all()

server/templates/production/aircraft.html
{% extends "base.html" %}
{% block header %}
    {% include "header.html" %}
{% endblock header %}
{% block content %}
<div class="py-10">
    <header>
      <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div>
            <div>
              <nav class="sm:hidden" aria-label="Back">
                  <a href="javascript:history.back()" class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700">
                    <svg class="-ml-1 mr-1 size-5 shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
                      <path fill-rule="evenodd" d="M11.78 5.22a.75.75 0 0 1 0 1.06L8.06 10l3.72 3.72a.75.75 0 1 1-1.06 1.06l-4.25-4.25a.75.75 0 0 1 0-1.06l4.25-4.25a.75.75 0 0 1 1.06 0Z" clip-rule="evenodd" />
                    </svg>
                    Back
                  </a>
              </nav>
              <nav class="hidden sm:flex" aria-label="Breadcrumb">
                  <ol role="list" class="flex items-center space-x-4">
                    <li>
                      <div class="flex">
                        <a href="{% url 'production:index' %}" class="text-sm font-medium text-gray-500 hover:text-gray-700">Production</a>
                      </div>
                    </li>
                    {% block page_breadcrumb %}{% endblock %}
                  </ol>
              </nav>
            </div>
            <div class="mt-2 md:flex md:items-center md:justify-between">
              <div class="min-w-0 flex-1">
                <h2 class="text-2xl/7 font-bold text-gray-900 sm:truncate sm:text-3xl sm:tracking-tight">{% block page_title %}Production{% endblock %}</h2>
              </div>
              <div class="mt-4 flex shrink-0 md:ml-4 md:mt-0">
                {% block page_actions %}{% endblock %}
              </div>
            </div>
          </div>
      </div>
    </header>
    <main>
      <div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
        {% block page_content %}{% endblock %}  
      </div>
    </main>
</div>
{% endblock content %}
{% block footer %}
{% include "footer.html" %}
{% endblock footer %}

server/templates/production/aircraft_index.html
{% extends "production/aircraft.html" %}
{% block page_content %}

<div class="mt-6 grid grid-cols-1 gap-x-8 gap-y-8 sm:grid-cols-2 sm:gap-y-10 lg:grid-cols-4">
    <div class="group relative">
        <div class="relative">
        <img src="https://cdn.baykartech.com/media/upload/userFormUpload/HfKd71PR8Fqln30Qu1VSVY7ujAvC9VgL.png" class="aspect-[4/3] w-full rounded-lg bg-gray-100 object-cover">
        <div class="absolute inset-0 flex items-end p-4 opacity-0 group-hover:opacity-100" aria-hidden="true">
            <div class="w-full rounded-md bg-white/75 px-4 py-2 text-center text-sm font-medium text-gray-900 backdrop-blur backdrop-filter">View Models</div>
        </div>
        </div>
        <div class="mt-4 flex items-center justify-between space-x-8 text-base font-medium text-gray-900">
            <h3>
                <a href="{% url 'production:model' %}">
                <span aria-hidden="true" class="absolute inset-0"></span>
                Models
                </a>
            </h3>
        </div>
        <p class="mt-1 text-sm text-gray-500">Available model of aircraft</p>
    </div>

    <div class="group relative">
        <div class="relative">
        <img src="https://cdn.baykartech.com/media/upload/userFormUpload/FcLUmeJZLYReOgicr8GyC32dEQauCGcO.jpeg" alt="Payment application dashboard screenshot with transaction table, financial highlights, and main clients on colorful purple background." class="aspect-[4/3] w-full rounded-lg bg-gray-100 object-cover">
        <div class="absolute inset-0 flex items-end p-4 opacity-0 group-hover:opacity-100" aria-hidden="true">
            <div class="w-full rounded-md bg-white/75 px-4 py-2 text-center text-sm font-medium text-gray-900 backdrop-blur backdrop-filter">View Parts</div>
        </div>
        </div>
        <div class="mt-4 flex items-center justify-between space-x-8 text-base font-medium text-gray-900">
        <h3>
            <a href="{% url 'production:part' %}">
            <span aria-hidden="true" class="absolute inset-0"></span>
            Part
            </a>
        </h3>
        </div>
        <p class="mt-1 text-sm text-gray-500">Part contained in an aircraft</p>
    </div>

<!-- More products... -->
</div>

{% endblock %}

server/templates/production/aircraft_model.html
{% extends "production/aircraft.html" %}
{% block page_breadcrumb %}
<li>
    <div class="flex items-center">
        <svg class="size-5 shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
        <path fill-rule="evenodd" d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
        </svg>
        <a href="{% url 'production:model' %}" class="ml-4 text-sm font-medium text-gray-500 hover:text-gray-700">Models</a>
    </div>
</li>
{% endblock %}
{% block page_title %}Aircraft models{% endblock %}
{% block page_actions %}
<a href="{% url 'production:model-create' %}" type="button" class="inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">New model</a>
{% endblock %}
{% block page_content %}
<table id="model-table" class="display" style="width:100%">
  <thead>
      <tr>
          <th>Name</th>
          <th>Description</th>
      </tr>
  </thead>
  <tbody>
    {% for model in model_list %}
      <tr>
        <td>{{ model.name }}</td>
        <td>{{ model.desc }}</td>
      </tr>
    {% endfor %}
  </tbody>
  <tfoot>
      <tr>
          <th>Name</th>
          <th>Description</th>
      </tr>
  </tfoot>
</table>
<script>
  new DataTable('#model-table');
</script>
{% endblock %}

server/templates/production/aircraft_model_create.html
{% extends "production/aircraft.html" %}
{% block page_breadcrumb %}
<li>
    <div class="flex items-center">
        <svg class="size-5 shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
        <path fill-rule="evenodd" d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
        </svg>
        <a href="{% url 'production:model' %}" class="ml-4 text-sm font-medium text-gray-500 hover:text-gray-700">Models</a>
    </div>
</li>
<li>
    <div class="flex items-center">
        <svg class="size-5 shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
        <path fill-rule="evenodd" d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
        </svg>
        <a href="{% url 'production:model-create' %}" class="ml-4 text-sm font-medium text-gray-500 hover:text-gray-700">Create</a>
    </div>
</li>
{% endblock %}
{% block page_title %}New aircraft model{% endblock %}
{% block page_content %}
{% load append_class %}
<form method="POST">
  {% csrf_token %}
  <div class="space-y-12">
    <div class="border-b border-gray-900/10 pb-12">
      <p class="mt-1 text-sm/6 text-gray-600">Complete the form to create a new model of aircraft.</p>
      <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">

        <div class="col-span-full">
          <label for="street-address" class="block text-sm/6 font-medium text-gray-900">Name</label>
          <div class="mt-2">
            {{ form.name|append_class:"block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6" }}
          </div>
        </div>

        <div class="col-span-full">
          <label for="about" class="block text-sm/6 font-medium text-gray-900">Description</label>
          <div class="mt-2">
            {{ form.desc|append_class:"block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6" }}
          </div>
          <p class="mt-3 text-sm/6 text-gray-600">Write a few sentences to describe the aircraft.</p>
        </div>

      </div>
    </div>
  </div>

  <div class="mt-6 flex items-center justify-end gap-x-6">
    <button type="button" class="text-sm/6 font-semibold text-gray-900">Cancel</button>
    <button type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Save</button>
  </div>
</form>


{% endblock %}

server/templates/production/aircraft_part.html
{% extends "production/aircraft.html" %}
{% block page_breadcrumb %}
<li>
    <div class="flex items-center">
        <svg class="size-5 shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
        <path fill-rule="evenodd" d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
        </svg>
        <a href="{% url 'production:part' %}" class="ml-4 text-sm font-medium text-gray-500 hover:text-gray-700">Parts</a>
    </div>
</li>
{% endblock %}
{% block page_title %}Aircraft parts{% endblock %}
{% block page_actions %}
<a href="{% url 'production:part-create' %}" type="button" class="inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">New part</a>
{% endblock %}
{% block page_content %}
<table id="part-table" class="display" style="width:100%">
  <thead>
      <tr>
          <th>Name</th>
          <th>Description</th>
      </tr>
  </thead>
  <tbody>
    {% for part in part_list %}
      <tr>
        <td>{{ part.name }}</td>
        <td>{{ part.desc }}</td>
      </tr>
    {% endfor %}
  </tbody>
  <tfoot>
      <tr>
          <th>Name</th>
          <th>Description</th>
      </tr>
  </tfoot>
</table>
<script>
  new DataTable('#part-table');
</script>
{% endblock %}

server/templates/production/aircraft_part_create.html
{% extends "production/aircraft.html" %}
{% block page_breadcrumb %}
<li>
    <div class="flex items-center">
        <svg class="size-5 shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
        <path fill-rule="evenodd" d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
        </svg>
        <a href="{% url 'production:part' %}" class="ml-4 text-sm font-medium text-gray-500 hover:text-gray-700">Parts</a>
    </div>
</li>
<li>
    <div class="flex items-center">
        <svg class="size-5 shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
        <path fill-rule="evenodd" d="M8.22 5.22a.75.75 0 0 1 1.06 0l4.25 4.25a.75.75 0 0 1 0 1.06l-4.25 4.25a.75.75 0 0 1-1.06-1.06L11.94 10 8.22 6.28a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
        </svg>
        <a href="{% url 'production:part-create' %}" class="ml-4 text-sm font-medium text-gray-500 hover:text-gray-700">Create</a>
    </div>
</li>
{% endblock %}
{% block page_title %}New aircraft part{% endblock %}
{% block page_content %}
{% load append_class %}
<form method="POST">
  {% csrf_token %}
  <div class="space-y-12">
    <div class="border-b border-gray-900/10 pb-12">
      <p class="mt-1 text-sm/6 text-gray-600">Complete the form to create a new part of aircraft part.</p>
      <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">

        <div class="col-span-full">
          <label for="street-address" class="block text-sm/6 font-medium text-gray-900">Name</label>
          <div class="mt-2">
            {{ form.name|append_class:"block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6" }}
          </div>
        </div>

        <div class="col-span-full">
          <label for="about" class="block text-sm/6 font-medium text-gray-900">Description</label>
          <div class="mt-2">
            {{ form.desc|append_class:"block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6" }}
          </div>
          <p class="mt-3 text-sm/6 text-gray-600">Write a few sentences to describe the aircraft.</p>
        </div>

      </div>
    </div>
  </div>

  <div class="mt-6 flex items-center justify-end gap-x-6">
    <button type="button" class="text-sm/6 font-semibold text-gray-900">Cancel</button>
    <button type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Save</button>
  </div>
</form>


{% endblock %}